# Generated by Django 4.2 on 2023-05-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("contact_number", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Airline",
            },
        ),
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "gate_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "Gate",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                ("name", models.CharField(max_length=20)),
                (
                    "manager_id",
                    models.CharField(
                        default="", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Manager",
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="UnKnown", max_length=20, unique=True),
                ),
                ("email", models.EmailField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(default="Unknown", max_length=20, unique=True),
                ),
                (
                    "identification",
                    models.CharField(default="Unknown", max_length=20, unique=True),
                ),
                (
                    "username",
                    models.CharField(default="Unknown", max_length=20, unique=True),
                ),
                ("password", models.CharField(max_length=255)),
                ("avatar", models.ImageField(null=True, upload_to="avatar")),
            ],
            options={
                "db_table": "Passenger",
                "unique_together": {
                    ("name", "identification", "phone_number", "username")
                },
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("contact_number", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Shop",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("name", models.CharField(max_length=20)),
                (
                    "staff_id",
                    models.CharField(
                        default="", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Staff",
            },
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "terminal_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "Terminal",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("departure_datetime", models.DateTimeField()),
                ("arrival_datetime", models.DateTimeField()),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="airport.gate"
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.passenger",
                        to_field="identification",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.terminal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Runway",
            fields=[
                (
                    "runway_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="airport.gate"
                    ),
                ),
            ],
            options={
                "db_table": "Runway",
            },
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parking_number", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("duration", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.passenger",
                        to_field="identification",
                    ),
                ),
            ],
            options={
                "db_table": "Parking",
            },
        ),
        migrations.CreateModel(
            name="Luggage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("luggage_number", models.CharField(max_length=20)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=3)),
                ("status", models.CharField(max_length=20)),
                ("position", models.CharField(max_length=20)),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.passenger",
                        to_field="identification",
                    ),
                ),
            ],
            options={
                "db_table": "Luggage",
            },
        ),
        migrations.AddField(
            model_name="gate",
            name="terminal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="airport.terminal"
            ),
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "flight_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("departure_datetime", models.DateTimeField()),
                ("arrival_datetime", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=20)),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="airport.gate"
                    ),
                ),
                (
                    "runway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="airport.runway"
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.terminal",
                    ),
                ),
            ],
            options={
                "db_table": "Flight",
            },
        ),
    ]
