# Generated by Django 4.2 on 2023-05-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dev_id", models.CharField(max_length=20)),
                ("dev_name", models.CharField(max_length=20)),
                ("image", models.ImageField(null=True, upload_to="devices")),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Device",
            },
        ),
    ]
