# Generated by Django 4.2 on 2023-05-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(max_length=20)),
                ("store_name", models.CharField(max_length=20)),
                ("store_image", models.ImageField(null=True, upload_to="stores")),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="airport.shop"
                    ),
                ),
            ],
            options={
                "db_table": "Store",
            },
        ),
    ]
