# Generated by Django 4.2 on 2023-05-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="nn",
        ),
    ]
