# Generated by Django 4.2 on 2023-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
