# Generated by Django 4.2 on 2023-05-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="id",
        ),
        migrations.AlterField(
            model_name="store",
            name="store_id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
