# Generated by Django 4.2 on 2023-05-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_passenger_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatar"),
        ),
    ]
